mod acp;
mod agent_binding;
pub(crate) mod agent_executor;
mod automation;
pub(crate) mod automation_protocol;
mod bootstrap;
mod cli_config;
pub(crate) mod config_repository;
pub(crate) mod conversation_switch;
mod doctor_cli;
pub(crate) mod headless_run;
mod interactive;
pub(crate) mod interactive_presenter;
mod interactive_run_controller;
pub(crate) mod interactive_runtime;
mod interactive_session_controller;
mod interactive_state;
mod login;
mod mcp_cli;
mod parent_bridge;
mod plugins_cli;
mod policy;
mod provider_controller;
mod runtime_builder;
pub(crate) mod sdk_config;
mod session_assembly;
mod sessions_cli;
pub(crate) mod side_chat;
pub(crate) mod subagent_host_input;
pub(crate) mod subagent_messaging;
mod tools_prompt;
pub(crate) mod workflow_cli;
pub(crate) mod workflow_runtime;

pub use automation::{AutomationExit, AutomationInterrupted};
pub use bootstrap::run;
