mod agent;
mod app;
mod changelog;
mod child_env;
mod claude_runtime;
mod cli;
mod clipboard;
mod commands;
mod compaction;
mod config;
mod config_writer;
mod credential_store;
mod diagnostics;
mod executable;
mod export;
mod herdr;
mod hooks;
mod keybindings;
mod model_aliases;
mod model_identity;
mod paths;
mod permission;
mod permission_classifier;
mod permission_classifier_handler;
mod plugins;
mod prompt;
mod prompt_templates;
mod questionnaire;
mod run_artifacts;
mod session;
mod skills;
mod stdio;
mod subagent;
mod tools;
mod transcript;
mod tui;
mod update;
mod usage;
mod usage_limits;
pub(crate) mod workflow;
mod workspace;

pub use app::{run, AutomationExit, AutomationInterrupted};
pub use cli::Cli;
pub use rho_providers as providers_lib;
pub use rho_sdk as sdk;
pub use rho_tools as tools_lib;
